import { OrderWithRelations } from './types';

export const INITIAL_ORDERS_FIXTURE: OrderWithRelations[] = [
  {
    id: 'ord-brass-bell-01',
    orderNumber: 'MG-2026-0182',
    userId: 'usr-brass-bell',
    type: 'RENTAL_COMMERCIAL',
    status: 'READY_FOR_DISPATCH',
    quotedTotalZar: 19800,
    depositRequiredZar: 4500,
    depositPaidAt: '2026-09-12T14:30:00Z',
    leadTimeWeeks: 2,
    createdAt: '2026-09-10T09:15:00Z',
    updatedAt: '2026-09-17T16:00:00Z',
    user: {
      id: 'usr-brass-bell',
      name: 'Dave Stewart',
      email: 'dave@thebrassbell.co.za',
      phone: '+27824559812',
      companyName: 'The Brass Bell Kalk Bay',
      vatNumber: '4910293847',
      venueType: 'Pub & Restaurant',
      createdAt: '2026-09-10T09:15:00Z',
      updatedAt: '2026-09-10T09:15:00Z',
    },
    configuration: {
      id: 'cfg-01',
      orderId: 'ord-brass-bell-01',
      tableSize: 'SEVEN_FOOT_PUB',
      bodyFinishType: 'WOOD_SOLID',
      bodyColorFinish: 'Kiaat Natural Oil',
      feltColor: 'Speed Green',
      feltTexture: 'standard_wool',
      customWrapUrl: null,
      coinOpMechanic: true,
      hardwareFinish: 'brass',
      generatedSku: 'MG-7FT-KIAAT-GRN-COIN-01',
      renderSnapshotUrl: null,
    },
    siteAudit: {
      id: 'aud-01',
      orderId: 'ord-brass-bell-01',
      deliveryAddress: 'Main Road, Kalk Bay Harbour',
      deliveryCity: 'Cape Town',
      postalCode: '7975',
      isGroundFloor: false,
      hasElevator: false,
      stairsCount: 14,
      stairType: 'straight',
      doorwayWidthCm: 92,
      floorPlanJson: {
        room: { length: 6.2, width: 4.8 },
        tables: [{ x: 3.1, y: 2.4, rotation: 0 }],
      },
      floorPlanImageUrl: null,
      ingressVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      videoReviewNotes: 'Narrow stairway landing before sea-facing deck. Requires 4-man crew.',
      crewRecommended: 4,
      requiresRiggingGear: true,
    },
    rentalAgreement: {
      id: 'agr-01',
      orderId: 'ord-brass-bell-01',
      term: 'SIX_MONTHS',
      monthlyRateZar: 2200,
      depositZar: 4500,
      coinOpSplitPct: 50.0,
      includedReclothMonths: 6,
      nextServiceDueDate: '2027-03-15T00:00:00Z',
      contractSignedAt: '2026-09-12T15:00:00Z',
      contractPdfUrl: null,
    },
    installationSignoff: null,
  },
  {
    id: 'ord-firemans-arms-02',
    orderNumber: 'MG-2026-0183',
    userId: 'usr-firemans',
    type: 'RENTAL_COMMERCIAL',
    status: 'LEAD_NEW',
    quotedTotalZar: 24000,
    depositRequiredZar: 5000,
    depositPaidAt: null,
    leadTimeWeeks: 3,
    createdAt: '2026-09-18T08:30:00Z',
    updatedAt: '2026-09-18T08:30:00Z',
    user: {
      id: 'usr-firemans',
      name: 'Carl Weber',
      email: 'carl@firemansarms.co.za',
      phone: '+27839124401',
      companyName: "Fireman's Arms",
      vatNumber: '4120938271',
      venueType: 'Historic Sports Bar',
      createdAt: '2026-09-18T08:30:00Z',
      updatedAt: '2026-09-18T08:30:00Z',
    },
    configuration: {
      id: 'cfg-02',
      orderId: 'ord-firemans-arms-02',
      tableSize: 'EIGHT_FOOT_PRO',
      bodyFinishType: 'WOOD_SOLID',
      bodyColorFinish: 'Solid Walnut',
      feltColor: 'Electric Blue',
      feltTexture: 'tournament_worsted',
      customWrapUrl: null,
      coinOpMechanic: true,
      hardwareFinish: 'chrome',
      generatedSku: 'MG-8FT-WALNUT-BLU-72',
      renderSnapshotUrl: null,
    },
    siteAudit: {
      id: 'aud-02',
      orderId: 'ord-firemans-arms-02',
      deliveryAddress: '25 Buitengracht St, De Waterkant',
      deliveryCity: 'Cape Town',
      postalCode: '8001',
      isGroundFloor: true,
      hasElevator: false,
      stairsCount: 0,
      stairType: null,
      doorwayWidthCm: 110,
      floorPlanJson: null,
      floorPlanImageUrl: null,
      ingressVideoUrl: null,
      videoReviewNotes: null,
      crewRecommended: 2,
      requiresRiggingGear: false,
    },
    rentalAgreement: {
      id: 'agr-02',
      orderId: 'ord-firemans-arms-02',
      term: 'TWELVE_MONTHS',
      monthlyRateZar: 2000,
      depositZar: 5000,
      coinOpSplitPct: 40.0,
      includedReclothMonths: 6,
      nextServiceDueDate: null,
      contractSignedAt: null,
      contractPdfUrl: null,
    },
    installationSignoff: null,
  },
  {
    id: 'ord-constantia-custom-03',
    orderNumber: 'MG-2026-0184',
    userId: 'usr-sarah-j',
    type: 'PURCHASE_CUSTOM',
    status: 'IN_MANUFACTURE',
    quotedTotalZar: 48500,
    depositRequiredZar: 24250,
    depositPaidAt: '2026-09-14T11:00:00Z',
    leadTimeWeeks: 5,
    createdAt: '2026-09-14T10:00:00Z',
    updatedAt: '2026-09-15T09:20:00Z',
    user: {
      id: 'usr-sarah-j',
      name: 'Sarah Jenkins',
      email: 'sarah.j@mweb.co.za',
      phone: '+27718902341',
      companyName: null,
      vatNumber: null,
      venueType: 'Residential Man Cave',
      createdAt: '2026-09-14T10:00:00Z',
      updatedAt: '2026-09-14T10:00:00Z',
    },
    configuration: {
      id: 'cfg-03',
      orderId: 'ord-constantia-custom-03',
      tableSize: 'EIGHT_FOOT_PRO',
      bodyFinishType: 'STEEL_POWDER_COAT',
      bodyColorFinish: 'Matte Black Steel',
      feltColor: 'Burgundy',
      feltTexture: 'tournament_worsted',
      customWrapUrl: null,
      coinOpMechanic: false,
      hardwareFinish: 'matte_black',
      generatedSku: 'MG-8FT-BLKSTEEL-BUR-CUSTOM',
      renderSnapshotUrl: null,
    },
    siteAudit: {
      id: 'aud-03',
      orderId: 'ord-constantia-custom-03',
      deliveryAddress: '14 Klein Constantia Road',
      deliveryCity: 'Cape Town',
      postalCode: '7806',
      isGroundFloor: true,
      hasElevator: false,
      stairsCount: 0,
      stairType: null,
      doorwayWidthCm: 140,
      floorPlanJson: {
        room: { length: 5.8, width: 4.6 },
        tables: [{ x: 2.9, y: 2.3, rotation: 0 }],
      },
      floorPlanImageUrl: null,
      ingressVideoUrl: null,
      videoReviewNotes: 'Double French doors open straight into entertainment lounge. Easy access.',
      crewRecommended: 2,
      requiresRiggingGear: false,
    },
    rentalAgreement: null,
    installationSignoff: null,
  },
  {
    id: 'ord-kloof-street-04',
    orderNumber: 'MG-2026-0180',
    userId: 'usr-tshiamo',
    type: 'PURCHASE_CUSTOM',
    status: 'INSTALLED_ACTIVE',
    quotedTotalZar: 42000,
    depositRequiredZar: 21000,
    depositPaidAt: '2026-08-20T10:00:00Z',
    leadTimeWeeks: 4,
    createdAt: '2026-08-18T14:00:00Z',
    updatedAt: '2026-09-16T12:00:00Z',
    user: {
      id: 'usr-tshiamo',
      name: 'Tshiamo Moloi',
      email: 'tshiamo.m@gmail.com',
      phone: '+27829910022',
      companyName: null,
      vatNumber: null,
      venueType: 'Penthouse Apartment',
      createdAt: '2026-08-18T14:00:00Z',
      updatedAt: '2026-08-18T14:00:00Z',
    },
    configuration: {
      id: 'cfg-04',
      orderId: 'ord-kloof-street-04',
      tableSize: 'SEVEN_FOOT_PUB',
      bodyFinishType: 'WOOD_SOLID',
      bodyColorFinish: 'Kiaat Natural Oil',
      feltColor: 'Charcoal',
      feltTexture: 'standard_wool',
      customWrapUrl: null,
      coinOpMechanic: false,
      hardwareFinish: 'chrome',
      generatedSku: 'MG-7FT-KIAAT-CHAR-01',
      renderSnapshotUrl: null,
    },
    siteAudit: {
      id: 'aud-04',
      orderId: 'ord-kloof-street-04',
      deliveryAddress: '88 Kloof Street, Gardens',
      deliveryCity: 'Cape Town',
      postalCode: '8001',
      isGroundFloor: false,
      hasElevator: true,
      stairsCount: 0,
      stairType: null,
      doorwayWidthCm: 95,
      floorPlanJson: null,
      floorPlanImageUrl: null,
      ingressVideoUrl: null,
      videoReviewNotes: null,
      crewRecommended: 2,
      requiresRiggingGear: false,
    },
    rentalAgreement: null,
    installationSignoff: {
      id: 'sig-04',
      orderId: 'ord-kloof-street-04',
      installerName: 'Sipho Ndlovu',
      slateLeveled: true,
      clothTensioned: true,
      cushionsChecked: true,
      spiritLevelPhotoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
      completedRoomPhotoUrl: 'https://images.unsplash.com/photo-1615840287214-7ff58936c4cf?auto=format&fit=crop&w=600&q=80',
      customerSignatureUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="60"><path d="M10 40 Q50 10 90 40 T180 30" stroke="black" stroke-width="2" fill="none"/></svg>',
      signedAt: '2026-09-16T11:45:00Z',
    },
  },
];
